create table public.credits (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  credits numeric(10, 2) not null default 0,
  user_id uuid not null,
  constraint credits_pkey primary key (id),
  constraint credits_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;

create index IF not exists credits_user_id_idx on public.credits using btree (user_id) TABLESPACE pg_default;