create table public.samples (
  id bigint generated by default as identity not null,
  uri text not null,
  "modelId" bigint not null,
  created_at timestamp with time zone not null default now(),
  constraint samples_pkey primary key (id),
  constraint samples_modelId_fkey foreign KEY ("modelId") references models (id) on delete CASCADE
) TABLESPACE pg_default;