create table public.user_feedback (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  feedback_text text not null,
  created_at timestamp with time zone not null default now(),
  constraint user_feedback_pkey primary key (id),
  constraint user_feedback_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;